veterinaria/config/routes.rb
Veterinaria::Application.routes.draw do
  resources :duenos

end

veterinaria/app/views/duenos/_form.html.erb
<%= form_for(@dueno) do |f| %>
  <% if @dueno.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dueno.errors.count, "error") %> prohibited this dueno from being saved:</h2>

      <ul>
      <% @dueno.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

veterinaria/app/views/duenos/index.html.erb
<h1>Listing duenos</h1>

<table>
  <tr>
    <th>Nombre</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @duenos.each do |dueno| %>
  <tr>
    <td><%= dueno.nombre %></td>
    <td><%= link_to 'Show', dueno %></td>
    <td><%= link_to 'Edit', edit_dueno_path(dueno) %></td>
    <td><%= link_to 'Destroy', dueno, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dueno', new_dueno_path %>

veterinaria/app/views/duenos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nombre:</b>
  <%= @dueno.nombre %>
</p>


<%= link_to 'Edit', edit_dueno_path(@dueno) %> |
<%= link_to 'Back', duenos_path %>

veterinaria/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Veterinaria</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>